[package]
name = "cargo-profile"
version = "0.1.0"
authors = ["Colin Rofls <colin@cmyr.net>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
cargo = "*"
failure = "*"
structopt = { version = "0.2", default-features = false }
